### ISSUE TITLE
Suggestion: moving package to madewithlove/twilio 

### ISSUE THREAD

**Issue by hannesvdvreken** [aloha/laravel-twilio#101]
Hi, Travis (@aloha)!

I haven't spend much time on this package lately but I want to renew my commitment. I feel like I can spend more time (also company time) on it if it were to have a different vendor name, though. What do you think about it if we would move it to https://github.com/madewithlove and rename it on packagist to madewithlove/twilio and deprecate the current one? License and terms and all of that would remain the same. What are your thoughts on this?

Cheers,
Hannes

**Comment by aloha** [comment]
Hey @hannesvdvreken,

I unintentionally disrupted this library once when I changed my github name to aloha.  I couldn't resist snagging up such a cool name.  That being said I am not sure transferring/moving the project to another account is worthwhile.  We could however create a contributors section on the front page and promote the company you work for by displaying a reasonably sized company logo, link to your site.  What do you think?

**Comment by hannesvdvreken** [comment]
> I couldn't resist snagging up such a cool name.

Haha 😀

Nowadays it has become easier to transfer repos and packages. But I feel you're not 100% with me on this one. No problem 😉 I'll take a look at the contributors section. Not sure if a logo is needed, though.

Thanks for the response, Travis!
