### ISSUE TITLE
Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()

### ISSUE THREAD

**Issue by sentiasa** [aloha/laravel-twilio#105]
I tried installing laravel-twilio in my Laravel 5.2 app, but I keep receiving error
> Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()
and
>Call to undefined method Aloha\Twilio\Support\Laravel\Facade::call()
depending on the function

1. I installed `composer require aloha/twilio`
2. Added `Aloha\Twilio\Support\Laravel\ServiceProvider::class` in providers
3. Added  `'Twilio' => Aloha\Twilio\Support\Laravel\Facade::class` in aliases
4. `use Twilio;`

And then this line gives..
```
$twilio = new Twilio($_ENV['TWILIO_ACCOUNT_SID'], $_ENV['TWILIO_AUTH_TOKEN'], $no);
$twilio->message($recipient, 'Pink Elephants and Happy Rainbows');
```
error:
> Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()

**Comment by hannesvdvreken** [comment]
Well, you don't want to use the Facade as a Twilio instance: you want to use it as an accessor:

```
Twilio::message()
```
instead of
```
new Twilio
$twilio->message
```

If you don't like that syntax: inject a TwilioInterface instance and call methods on that.

**Comment by DhanapalMadheswaran** [comment]
Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()

**Comment by DhanapalMadheswaran** [comment]
i m getting 
The requested resource /2010-04-01/Accounts//Messages.json was not found
when i m use
Twilio::message()

if i m use 
new Twilio
$twilio->message 
i m getting Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()

error
