### ISSUE TITLE
Messages a being queued on test  account,

### ISSUE THREAD

**Issue by tayyabhussain** [aloha/laravel-twilio#107]
I have made a test account on Twilio and using this package for sending sms,
```
$twilio = new Aloha\Twilio\Twilio('My Test Account SID'
            , 'My Test AuthToken
            ', '+15005550006');
        $response = $twilio->message('+923214384818', 'Pink Elephants and Happy Rainbows');

        echo $response;
```
And the response is given below,
`{"sid":"SMb5c98a490d7f448c9d7d3d2824b48e45","date_created":"Thu, 28 Apr 2016 08:45:29 +0000","date_updated":"Thu, 28 Apr 2016 08:45:29 +0000","date_sent":null,"account_sid":"ACb77175f23c83da2f02e28135a8558342","to":"+923214384818","from":"+15005550006","messaging_service_sid":null,"body":"Sent from your Twilio trial account - Pink Elephants and Happy Rainbows","status":"queued","num_segments":"1","num_media":"0","direction":"outbound-api","api_version":"2010-04-01","price":null,"price_unit":"USD","error_code":null,"error_message":null,"uri":"\/2010-04-01\/Accounts\/ACb77175f23c83da2f02e28135a8558342\/Messages\/SMb5c98a490d7f448c9d7d3d2824b48e45","subresource_uris":{"media":"\/2010-04-01\/Accounts\/ACb77175f23c83da2f02e28135a8558342\/Messages\/SMb5c98a490d7f448c9d7d3d2824b48e45\/Media.json"}}`

What could be the error ?

**Comment by hannesvdvreken** [comment]
I have no idea, frankly. Maybe it's a setting in Twilio?
Better ask Twilio, as this has more to do with their service, than with this SDK wrapper.
