### ISSUE TITLE
Fix versioning?

### ISSUE THREAD

**Issue by Atrophius** [aloha/laravel-twilio#108]
Why does it seem like v1.1 and v1.2 of this package are newer than v2.0? This appears to be confusing packagist which properly assumes that 2.0 is the latest version.

**Comment by hannesvdvreken** [comment]
Hi @Atrophius,

Holy crap, you're right. `1.2.0` should have been `2.1.0`... `1.1.0` is correct though. Let me think what I should do. Suggestions?

**Comment by Atrophius** [comment]
Might be good to just go ahead and tag a 2.1 that's a copy of 1.2?

**Comment by aloha** [comment]
Saw you created 2.1 and removed 1.2 so I removed 1.2 from packagist.  2.1 was already picked up by packagist.

Cheers

**Comment by hannesvdvreken** [comment]
Correct! That's why I asked you for access to packagist because I couldn't remove 1.2.0 there. It might bring people in difficulties when they installed 1.2.0 but they should be able to install 2.1.0 instead and not have to update any code.

**Comment by hannesvdvreken** [comment]
It's better this way, so that different versions still behave like semver, and 1.2.0 is not a breaking change compared to 1.1.x
