### ISSUE TITLE
[Question] Does this binding supports Reply feature

### ISSUE THREAD

**Issue by jagroop** [aloha/laravel-twilio#109]
Is it possible to use twilio's [Replying to Text Messages By Name] (https://www.twilio.com/docs/quickstart/php/sms/replying-to-sms-messages) using this binding ??

**Comment by hannesvdvreken** [comment]
Maybe. You should be able to do it if you can do it with the Twilio SDK. Consider putting your question on stackoverflow if you can't figure out how.

**Comment by jagroop** [comment]
@hannesvdvreken  you created this api wrapper and you dont even know does this binding supports reply feature or not ?!

**Comment by hannesvdvreken** [comment]
Easy there :-)

I didn't create it. I maintain it (in case it needs upgrading if the SDK or Laravel comes out in a new major version, or in case of a security issue).

That doesn't mean I need to reply to your support questions, it's open source :-)

Twilio SDK has a ton of features. This package just configures the SDK client. You can do anything with it if you like. Read the documentation, if it lacks something, you can figure out how to do it and may consider sending a PR to let others enjoy your new piece of documentation.

Best of luck!
