### ISSUE TITLE
Alphanumeric sender ID

### ISSUE THREAD

**Issue by amanmukhtar** [aloha/laravel-twilio#114]
Is this possible to use alphanumeric sender IDs with this package???
` $twilio     = new Services_Twilio($accountSid, $token);`
`$response   = $twilio->account->messages->sendMessage("Test", $toNumber, $smsContent, null, $optionalParams);`

**Comment by hannesvdvreken** [comment]
In theory, you can use any string as `$from`. You should be able to configure it and then it's a matter of Twilio SDK accepting it. Let me know if it worked.

Closing it for now.
