### ISSUE TITLE
Meaning of IoC container

### ISSUE THREAD

**Issue by gyleodhis** [aloha/laravel-twilio#115]
Hello what do you mean by;
And make these objects resolvable from the IoC container:

Aloha\Twilio\Manager (aliased as twilio)
Aloha\Twilio\TwilioInterface (resolves a Twilio object, the default connection object created by the Manager).

What is the IoC container

**Comment by hannesvdvreken** [comment]
Here are 2 resources:

- http://stefanoricciardi.com/2011/11/08/dependency-injection-for-dummies/
- https://laravel.com/docs/5.2/container

I hope these will get you started. If you need more information, there are a lot of other resources out there. This is not something specific, but rather something general. So you should find help in lots of places.

If you don't mind, I'll close this issue as it's not a feature/bug/discussion.

Good luck!

**Comment by nWidart** [comment]
This video might help you as well: https://cleancoders.com/episode/clean-code-episode-13/show
