### ISSUE TITLE
Error [Services_Twilio_RestException]

### ISSUE THREAD

**Issue by hamidyfine** [aloha/laravel-twilio#117]
Hi.
When I want to use artisan command for test, it shows this error
```
  [Services_Twilio_RestException]
  Could not decode response body as JSON. This likely indicates a 500 server error
```
What is it for?

**Comment by hannesvdvreken** [comment]
Hi! This exception originates from the Twilio SDK rather than from this package. I'm afraid I can't help you at this time.
