### ISSUE TITLE
Split messages

### ISSUE THREAD

**Issue by alexandrasmith00** [aloha/laravel-twilio#118]
I'm running into a problem where long messages are split into multiple pieces.  I know that Twilio Message resource is supposed to handle these, but for some reason it's not. Does anyone have any information on this?

**Comment by alexandrasmith00** [comment]
Oh and here's the source for the messages resource.  Is laravel-twilio using the deprecated SMS/messages? https://support.twilio.com/hc/en-us/articles/223134307-Why-are-my-messages-with-unicode-being-split-

**Comment by hannesvdvreken** [comment]
Hi,

This package uses `$sdk->account->messages` (if you're using the latest version). Don't know if that's the deprecated way or not.

Cheers

**Comment by hannesvdvreken** [comment]
closing for now
