### ISSUE TITLE
[Proposal] Support logging and dummy pretend mode OOTB

### ISSUE THREAD

**Issue by derekmd** [aloha/laravel-twilio#122]
I'd like to be able to suppress all messages in some development or UAT environments to prevent third-party API requests. Similar to Laravel's handling of Swift Mailer, it would be nice if that can be stubbed out with one or two lines in the `.env` / `config/twilio.php` file, or the operating system's environmental vars.

> `MAIL_PRETEND=true` was abandoned in Laravel 5.2 for just `MAIL_DRIVER=log` but I think it would make sense keep these separate here.

This would require `'twilio'` on the app container or through the facade `Aloha\Twilio\Support\Laravel\Facade` to give a `Aloha\Twilio\Dummy` and/or `Aloha\Twilio\LoggingDecorator` instance when `Aloha\Twilio\Manager@from()` is invoked.

At the moment, concrete `Aloha\Twilio\Manager` will always gives a concrete `Aloha\Twilio\Twilio` instance so I thought about creating a `TwilioFactory` class to provide one of the three `TwilioInterface` instances based on the Laravel configuration.

But `Manager` is already a factory class in itself so that doesn't smell right. Since the package keeps Laravel-specifics to the `Aloha\Twilio\Support\Laravel` namespace, injecting the app's `Repository $config` into `Manager` seems a no-no. The alternative is a four parameter `Manager` constructor for each key in `$config` which is fairly undesirable.

So the best solution I could come up with was creating a `DummyManager` with `Manager`-shared methods moved to a trait. Then that class and `Manager` will decide themselves to wrap its `TwilioInterface` concretion with `Aloha\Twilio\LoggingDecorator` based on a third constructor `\Psr\Log\LoggerInterface` optionally injected parameter.

https://github.com/derekmd/laravel-twilio/commit/c0d842400f9453716ff164737463dc3998c98eeb

I consider this solution to be Frankenstein-ish so I was wondering if you had any thoughts?

**Comment by hannesvdvreken** [comment]
Right. Looking into this.

I'd like the container to do this for us, so it would inject a different TwilioInterface object based on the environment. The manager's getConnection method would still return a Twilio object, though.

**Comment by derekmd** [comment]
Looking at this again, it seems the easiest solution is to make `from()` a required method of `Aloha\Twilio\TwilioInterface`. As long as `app('twilio')` and `app(TwilioInterface::class)` have this method available, facade singleton or app container invocations can be `Dummy` or `LoggingDecorator`.

```php
Twilio::from('custom-config')->message($number, $message);
app('twilio')->from('custom-config')->call($number, $message);
```

That can be setup based on `Repository` object in `ServiceProviderTrait`.

The only awkward detail is how to handle concrete `Aloha\Twilio\Twilio@from()` as it's not aware of the app container or parent manager object.

Or maybe a new `ManagerTrait` (for `from()`) is introduced to `Manager`, `Dummy`, and `LoggingDecorator`?

**Comment by hannesvdvreken** [comment]
https://twitter.com/derekmd_/status/926659796929040384

:-) @derekmd sure, make it into a PR.
