### ISSUE TITLE
Can't Call Statically?

### ISSUE THREAD

**Issue by mattpramschufer** [aloha/laravel-twilio#124]
None of your functions that I see are static so you can't do 
`Twilio::message($user->phone, $message);`
without errors, especially on PHP7

**Comment by hannesvdvreken** [comment]
You need to use Laravel's facades for that. Which is not a static call. It's a configured call to an item in the IOC container.

```php
use Aloha\Twilio\Support\Laravel\Facade as Twilio;

Twilio::call(...);
```

Check https://laravel.com/docs/5.3/facades for more info.

**Comment by mattpramschufer** [comment]
I might recommend adding that to the Readme.  I was using `use Aloha\Twilio\Twilio;`

Thanks for the quick support though!  Working great.

**Comment by hannesvdvreken** [comment]
I would appreciate a PR. A change to a readme file is one of the easiest PRs one could make.
