### ISSUE TITLE
Twilio SDK 5.4

### ISSUE THREAD

**Issue by claygorman** [aloha/laravel-twilio#126]
Looks like composer is saying this library is locked to 4.X but twilio is on 5.X... any plans to support latest twilio SDK?

**Comment by mnek84** [comment]
Same question
 - Installation request for twilio/sdk (locked at 5.4.2) -> satisfiable by twilio/sdk[5.4.2].

**Comment by hannesvdvreken** [comment]
I had no idea that Twilio's SDK was so unstable (upping major number this fast).

Could you check their changelogs/release notes to find breaking things I need to watch out for when upping our composer.json?

**Comment by jmctwilio** [comment]
The Twilio API team has been working to shift from hand-written libraries (which are prone to human error) toward auto-generated libraries which can more easily keep up with the fast-growing feature set available on the Twilio platform.  This project is nearing its completion and while updates to the libraries to incorporate new features will certainly be expect, major version bumps should be much more stable.  Also, the team makes every effort to maintain backwards-compatibility with the changes as much as possible.

Our current version for the PHP library is 5.11.  Hopefully, it strikes the balance between providing access to all the great new features being offered on the Twilio platform and maintaining a stable environment for you to build on.  Please let us know if you have any issues and feel free to submit PRs to help make the library better.

**Comment by hannesvdvreken** [comment]
So... what's the conclusion? Should we allow all versions and only have a minimum version requirement?

**Comment by jmctwilio** [comment]
It's a difficult situation to be sure.  It may be best to have a minimum version -- I don't think this would introduce a great deal of instability.  While there are no guarantees (because the SDK is built on an evolving API), Twilio makes every effort to maintain backwards compatibility.

**Comment by hannesvdvreken** [comment]
Right. Ok. I've removed the SDK version number limit.

I guess it will still work but I hope I don't have to do any trickery for backwards compatibility to keep it working if Twilio's SDK changes.

https://github.com/aloha/laravel-twilio/releases/tag/3.0.1
