### ISSUE TITLE
[Bug 2.x] TwilioInterface doesn't have a defaultConnection method

### ISSUE THREAD

**Issue by amitailanciano** [aloha/laravel-twilio#129]
`ServiceProviderTrait` calls `->defaultConnection()` on the `twilio` service bound to `TwilioInterface::class`, but the built in `Dummy` class I want to use with the `LoggingDecorator` doesn't have a `defaultConnection` method, so I get undefined method errors in the logs.

I'm thinking the fix is just to add the `defaultConnection` method to the `TwilioInterface` and implement an empty method like the others on the `LoggingDecorator` and `Dummy` classes?

**Comment by hannesvdvreken** [comment]
`$this->app->make('twilio')` is the `Mananger::class` object. So no.

Feel free to make your own ServiceProvider and _not_ use the one included here.
