### ISSUE TITLE
Make a Call error: Services_Twilio_RestException in Twilio.php line 297

### ISSUE THREAD

**Issue by dflow** [aloha/laravel-twilio#130]
when running on Laravel 5
 return Twilio::call($toPhoneNumber, $message,[], $fromNumber);
I get :
Services_Twilio_RestException in Twilio.php line 297: Url is not a valid URL: HTTP/1.0 200 OK
Cache-Control: no-cache
Content-Type: text/xml

**Comment by hannesvdvreken** [comment]
What was the URL sent to Twilio?

Seems like an issue with how you're using it. Closing for now, can always reopen later.
