### ISSUE TITLE
how to use statucCallback?

### ISSUE THREAD

**Issue by asterism612** [aloha/laravel-twilio#131]
how to use?

**Comment by hannesvdvreken** [comment]
Did you read the documentation?

https://github.com/aloha/laravel-twilio#pass-as-many-optional-parameters-as-you-want 

```
$twilio->message($to, $message, $mediaUrls, [
    'StatusCallback'=>'http://yourdomain.com/yoururl.php',
]);
```

**Comment by asterism612** [comment]
ah. sorry.

I miss that section 

thank you.

**Comment by hannesvdvreken** [comment]
You're welcome. Anything else missing: feel free to propose a pull request.
