### ISSUE TITLE
Twilio Credential error

### ISSUE THREAD

**Issue by subhankartier5** [aloha/laravel-twilio#132]
If there is no balance in twilio account and if you use that keys at that point of time its showing error of authenticate

**Comment by hannesvdvreken** [comment]
That's a twilio SDK error you should catch yourself anyway.

**Comment by subhankartier5** [comment]
Never Mind I found out another way . Here is my code .. 
try {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, "https://api.twilio.com/2010-04-01/Accounts");
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

            curl_setopt($ch, CURLOPT_USERPWD, $request->twilio_live_sid . ":" . $request->twilio_live_token);

            $result = curl_exec($ch);
            //dd($result);
            $result = simplexml_load_string($result);
            $result = json_encode($result);
            $result = json_decode($result, TRUE);
            curl_close ($ch);
            if (array_key_exists('RestException', $result)) {
                return redirect('dashboard')->with('error',$result['RestException']['Detail']. "error code : ".$result['RestException']['Code']);
            }
        } catch (Exception $e) {

            //dd($e->getMessage());
            return redirect('dashboard')->with('error',$e->getMessage());
        }

according to me if you guys are giving one package for sake of mankind , you also should keep this issue on mind before releasing another version , cause this a very minimal thing where normal developers get scared that what's wrong with my code and the error was authenticate blade error which is also not very specific .
