### ISSUE TITLE
Services_Twilio_RestException issue

### ISSUE THREAD

**Issue by saktidebnath** [aloha/laravel-twilio#136]
HI,
 Is there any way to handle the exception for twilio sms call?
I was unable to handle the Services_Twilio_RestException like, The 'To' number ********* is not a valid phone number.

**Comment by hannesvdvreken** [comment]
have you tried this?

```
try{
   ...
} catch (\Services_Twilio_RestException $exception) {
   ...
}
```

Honestly I have no idea what your real issue is.
