### ISSUE TITLE
Support for Laravel 5

### ISSUE THREAD

**Issue by metacallo** [aloha/laravel-twilio#140]
There is an issue when using the twilio:sms and twilio:call test command, in Laravel 5, it expects the main method of the command to be "handle", not "fire".

Currently, the output of said command is

```
[ReflectionException]                                                   
Method Aloha\Twilio\Commands\TwilioSmsCommand::handle() does not exist 
```

**Comment by hannesvdvreken** [comment]
You're right. Since L5.1 it has changed to `handle` instead of `fire.`

**Comment by hannesvdvreken** [comment]
@metacallo Would #141 fix it for you?

**Comment by metacallo** [comment]
Oh yes! 💯
