### ISSUE TITLE
Laravel 5.4 and Service Provider

### ISSUE THREAD

**Issue by designloud** [aloha/laravel-twilio#142]
Documentation states I should add `'Aloha\Twilio\Support\Laravel\ServiceProvider',` to config/app.php but this file is expecting it to be similar to `Aloha\Twilio\TwilioServiceProvider::class,` -- What should I add here to use your package?

**Comment by hannesvdvreken** [comment]
either one is fine.

http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by himanshu-** [comment]
I have been trying to use this package with my laravel 5.4 application. And I have php 5.6.8 with my localhost. So when I try to include this package via composer, it gives me error. Can you please tell me if it is compatible with laravel 5.4 or it is just for Laravel 5.5 ?
