### ISSUE TITLE
create_function deprecated, still in Twilio 4.x SDK for PHP 

### ISSUE THREAD

**Issue by reedmaniac** [aloha/laravel-twilio#146]
The 4.x branch of the Twilio SDK for PHP has [this issue](https://github.com/twilio/twilio-php/issues/452) with PHP 7.2, where create_function() is deprecated. It throws an Exception and prevents messages from going out.

Another Laravel developer has discovered this issue and let the Twilio contributors know, but I am not sure if they are going to fix this issue since they have a 5.x branch going strong.

**Comment by musman92** [comment]
i also got this issue

**Comment by OgaBoss** [comment]
Please any way to fix this for now @reedmaniac

**Comment by reedmaniac** [comment]
@OgaBoss We had to reduce our PHP version thanks to another problem, but you could also reduce error reporting to remove E_DEPRECATED for the time being.  If the Laravel library is not fixed by the time we upgrade our PHP version again, I suspect I am just going to write my own Laravel wrapper for the most current version of the Twilio library, which does not have this create_function() usage.

**Comment by mnwalker** [comment]
@reedmaniac rather than writing a new wrapper could also assist with the PR to bump the Twilio SDK version up to 5.x
https://github.com/aloha/laravel-twilio/issues/147

**Comment by santiagotoledo91** [comment]
An easy fix is to use the **error_reporting** function just before the Twilio call, i've done it like this: ```
error_reporting(E_ERROR | E_WARNING | E_PARSE);
Twilio::message($phone_number, $message); 
```

That would fix the problem temporarily while the actual depreciation is solved by the Twilio team.
