### ISSUE TITLE
Bump Twilio SDK version

### ISSUE THREAD

**Issue by liran-co** [aloha/laravel-twilio#147]
Looks like this package doesn't support the latest Twilio SDK. Can we get a bumped version?

**Comment by hannesvdvreken** [comment]
There's some changes which need to be made in order to do so.

https://www.twilio.com/docs/libraries/php/migration-guide

Fancy making a PR which works for twilio sdk 5.*?

**Comment by mnwalker** [comment]
This is essential for php7.2 support without triggering deprecated errors, plus critical for php7.3.
https://github.com/twilio/twilio-php/issues/452#issuecomment-355149679

Got a lot on now but might have time to look at a PR in a few weeks if no-one else has been able to make it.

**Comment by reedmaniac** [comment]
OK, I built a branch that supports the existing library's functionality using the current version of the Twilio PHP SDK. My testing with a local Laravel PHP project shows it working with both test creds and live creds for both messaging and calling. Going to investigate adding a couple tests before I make a PR.  https://github.com/reedmaniac/laravel-twilio/tree/4.x

**Comment by Dartanjan** [comment]
I need this PR as well. Disabling deprecation errors for now but hopefully not for long. Thanks @reedmaniac for working on the PR. 👏

**Comment by reedmaniac** [comment]
Sorry for the delay on finishing up that PR, but I have been out of town the past three weekends and am out of town this weekend too.  If anyone wants to work on tests, I am willing to give access.

**Comment by IAmDragon** [comment]
Hey all,

As noted in a previous issue you can fix this by simply changing the two functions in Resource.php in `/vendor/twilio/sdk/Services/Twilio/Resource.php`

The two functions to change are Camelize and Decamelize

You can fix this issue by changing two functions in Resource.php.
```
public static function camelize($word) {
        return preg_replace_callback('/(^|_)([a-z])/',
	function ($matches) {
        	return ucfirst(strtolower($matches[2]));
        }, $word);
}
```
```
public static function decamelize($word) {
        return preg_replace_callback(
            '/(^|[a-z])([A-Z])/',
		function ($matches) {
            		return strtolower(strlen($matches[1]) ? $matches[1].$matches[2] : $matches[2]);
        	}, $word
        );
}
```

**Comment by reedmaniac** [comment]
https://github.com/aloha/laravel-twilio/pull/149

**Comment by DenzoNL** [comment]
Any progress on this? Can help out if necessary.

**Comment by whitleyblaine** [comment]
@IAmDragon I agree that you can fix the issue by replacing create_function with an anonymous function. But both camelize() and decamelize() are using strtolower() in the code you posted. shouldn't camelize() use strtoupper()? that's how the original function was written with create_function.

I too was tempted to believe the guy on this page at face value:
https://github.com/twilio/twilio-php/issues/452
But after reading his code and comparing it, I was reminded not to believe everything I read on the internet .. lol
