### ISSUE TITLE
Not working with larvel 5.4 with php 7.1

### ISSUE THREAD

**Issue by himanshu-** [aloha/laravel-twilio#148]
Hi,
I have been looking for a way to send SMS using Twilio from laravel 5.4. I have PHP v 7.1 with my system. I have been trying to use this package for my setup but this is not even installing with my system. I do not find the readme.md file helpful to set this up with laravel. Its been 4 days now and I could not find a simple solution.
Please guide me or correct the document.

Thank you in advance....

**Comment by bcdbuddy** [comment]
I met the same problem with laravel 5.4 php7.1

**Comment by chetan776** [comment]
I met the same problem with laravel 5.4 php7.1

**Comment by hannesvdvreken** [comment]
What does composer say?

**Comment by mdghousesaqlain** [comment]
I met with same problem, is there any way to get resolve.? #reedmanic
