### ISSUE TITLE
L5.6 configuration credentials

### ISSUE THREAD

**Issue by alejandri** [aloha/laravel-twilio#155]
After install package I added this lines to /config/app.php (it is OK?)
  
```
  'twilio' => [
        'default' => 'twilio',
        'connections' => [
            'twilio' => [
                'sid' => env('TWILIO_SID'),
                'token' => env('TWILIO_TOKEN'),
                'from' => env('TWILIO_NUMBER'),
            ],
        ],
    ],
```

where my .env file is

```
TWILIO_SID=AC******dcf0e6755a1a40****************
TWILIO_TOKEN=1379b********************************
TWILIO_NUMBER=+5**************
```

I tried basic config to send basic SMS (sending fine from Twilio Test page with same credentials.). 

`Twilio::message('+5**********','sms text testing');`

return error  [HTTP 400] Unable to create record: A 'From' phone number is required.

**Comment by abdelsalamshahlol** [comment]
In order to use this, you have to edit the env. file only like this:
```
TWILIO_SID='Your_SID'
TWILIO_TOKEN='Your_Token'
TWILIO_FROM='Number_registered'
```
