### ISSUE TITLE
 Function create_function() is deprecated

### ISSUE THREAD

**Issue by Mashpy** [aloha/laravel-twilio#161]
I was using laravel-twilio 3.0 version on my project. Recently I have updated my php version and now it is 7.2. But I am getting error =>

 "Function create_function() is deprecated"

Then I updated to laravel-twilio 4.0.2. But I am getting same error message. Can you fix this issue please?

**Comment by hannesvdvreken** [comment]
You can catch or suppress the error but you should consider upgrading to the latest version of the twilio sdk (and this package too).
