### ISSUE TITLE
Error 500 trying to make a call

### ISSUE THREAD

**Issue by simplenotezy** [aloha/laravel-twilio#162]
I try to make a call accoring to documentation, however, the following error happens:

     Twilio\Exceptions\RestException  : [HTTP 500] Unable to create record: An internal server error has occurred

    at /Users/cs/Projects/project/vendor/twilio/sdk/Twilio/Version.php:85
      81|         $content = $response->getContent();
      82|         if (is_array($content)) {
      83|             $message .= isset($content['message']) ? ': ' . $content['message'] : '';
      84|             $code = isset($content['code']) ? $content['code'] : $response->getStatusCode();
    > 85|             return new RestException($message, $code, $response->getStatusCode());
      86|         } else {
      87|             return new RestException($message, $response->getStatusCode(), $response->getStatusCode());
      88|         }
      89|     }

    Exception trace:

    1   Twilio\Version::exception(Object(Twilio\Http\Response), "Unable to create record")
        /Users/cs/Projects/project/vendor/twilio/sdk/Twilio/Version.php:219

    2   Twilio\Version::create("POST", "/Accounts/SK920e3a959f4008d3e97b40e5895c669a/Calls.json", [], ["+4526789888", "+4578755036", "https://api.twilio.com/cowbell.mp3"])
        /Users/cs/Projects/project/vendor/twilio/sdk/Twilio/Rest/Api/V2010/Account/CallList.php:87

    3   Twilio\Rest\Api\V2010\Account\CallList::create("+4526789888", "+4578755036", Object(Twilio\Values))
        /Users/cs/Projects/project/vendor/aloha/twilio/src/Twilio.php:97

    4   Aloha\Twilio\Twilio::call("+4526789888", "https://api.twilio.com/cowbell.mp3")
        /Users/cs/Projects/project/app/Call.php:38

    5   App\Call::dial("https://api.twilio.com/cowbell.mp3")
        /Users/cs/Projects/project/app/Call.php:20

    6   App\Call::make("+4526789888", "https://api.twilio.com/cowbell.mp3")
        /Users/cs/Projects/project/app/Console/Commands/MakeCall.php:71

    7   App\Console\Commands\MakeCall::handle()
        /Users/cs/Projects/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

This is the code:

		$twilio = new \Aloha\Twilio\Twilio(config('services.twilio.account_id'), config('services.twilio.token'), $this->from_id);
		

		if(!isset($payload)) {
			$payload = function ($message) {
			    $message->say('Hello dear');
			    $message->play('https://api.twilio.com/cowbell.mp3');
			};
		}

		return $twilio->call($this->caller_id, $payload);

**Comment by hannesvdvreken** [comment]
5xx response status codes are server errors.
