### ISSUE TITLE
Cant find twilio.php in my config fle

### ISSUE THREAD

**Issue by shanks25** [aloha/laravel-twilio#163]
Where did i go wrong please guide Even i did this cmd php atrisan vendor:publish --tag=config

**Comment by joeljerushan** [comment]
same issue here for me can you explain why this happens ?

**Comment by shanks25** [comment]
Well its really easy to integrate twilio directly they have provided docs directly for laravel , read those.

**Comment by hannesvdvreken** [comment]
thanks for replying @shanks25
