### ISSUE TITLE
Laravel 5.8 currently broken

### ISSUE THREAD

**Issue by thomaslenihanclarke** [aloha/laravel-twilio#164]
Hi

Firstly thanks for your work on this great package, unfortunately post upgrade to laravel 5.8 I am now receiving the message 'Credentials are required to create a Client' even though my credentials are present and correct and no previously working code has changed. 

Are you able to investigate further as to whether this package needs updating for 5.8? Thanks

**Comment by hannesvdvreken** [comment]
Please figure it out and post your updates here. I am currently enjoying time off and I would appreciate people who use this package to give something back.

**Comment by jdavidbakr** [comment]
I just ran into this as well.  The solution is that 'getenv()' in the config file should be changed to 'env()'.  My guess is that getenv() has been deprecated and was finally removed in the latest version of dotenv, which Laravel 5.8 was upgraded to use.

**Comment by hannesvdvreken** [comment]
Wrong. getenv is a native PHP function. Learn some PHP first before using Laravel.

**Comment by jdavidbakr** [comment]
Then dotenv is no longer filling the native env variables.  The Laravel way is to use env(), not getenv().

**Comment by hannesvdvreken** [comment]
I see. That's different than getenv being deprecated.

Also vlucas/phpdotenv will never stop populating env variables to be accessed through getenv. That wouldn't make sense as that is how all PHP apps (outside of Laravel) get their environment variables as a best practise.

**Comment by jdavidbakr** [comment]
Well, I'm not sure then why it stopped working in Laravel 5.8 but when I changed it to `env()` it fixed it.  I submitted a pull request with that change, mainly just because that's how Laravel does all their config files anyway.

**Comment by hannesvdvreken** [comment]
Upgrade to `^4.0.3` which includes the fix by @jdavidbakr
