### ISSUE TITLE
How to make this work with Twilio Whatsapp?

### ISSUE THREAD

**Issue by yelnyaface** [aloha/laravel-twilio#168]
hi, How do I make this work with Twilio Whatsapp?

**Comment by hannesvdvreken** [comment]
From what I understand from the API docs is you just add "whatsapp:" before
the "from" and "to" phone numbers.

**Comment by yelnyaface** [comment]
I tried Twilio::from('from')->message('whatsapp:'.'+12345623340', $message);

but the multiple 'from;' values I defined in config wont work and throws 500 Error each time, the format for the config file is not clearly shown in the Docs so I dont know why it throws error

**Comment by hannesvdvreken** [comment]
Hi. A 500 error usually indicates an error on twilio's side. Can you check
with them?

**Comment by yelnyaface** [comment]
I used this: Twilio::message('whatsapp:+1213231230', $message); and Twilio::message('+60123232332', $message)
without any issues, but I want to send SMS and whatsapp, so I want to configure 2x different 'from' in the twilio config file but 'Twilio::from('from')' keeps giving me Error 500

**Comment by yelnyaface** [comment]
also is there a way to check if: Twilio::message('whatsapp:+6011111111', $message); is successful or failed?

**Comment by hannesvdvreken** [comment]
Is `from` a key in your configuration? Use xdebug or something else to
verify that the correct config is being filled in as the from field before
the call goes off to Twilio at this line:
https://github.com/aloha/laravel-twilio/blob/master/src/Twilio.php#L70

**Comment by yelnyaface** [comment]
hi, this is how my twilio config file look like:
```
return [

    'twilio' => [

        'default' => 'twilio',

        'connections' => [

            'twilio' => [

                /*
                |--------------------------------------------------------------------------
                | SID
                |--------------------------------------------------------------------------
                |
                | Your Twilio Account SID #
                |
                */

                'sid' => env('TWILIO_SID') ?: '',

                /*
                |--------------------------------------------------------------------------
                | Access Token
                |--------------------------------------------------------------------------
                |
                | Access token that can be found in your Twilio dashboard
                |
                */

                'token' => env('TWILIO_TOKEN') ?: '',

                /*
                |--------------------------------------------------------------------------
                | From Number
                |--------------------------------------------------------------------------
                |
                | The Phone number registered with Twilio that your SMS & Calls will come from
                |
                */

                'from' => env('TWILIO_FROM') ?: '',

                'whatsapp' => env('TWILIO_WHATSAPP') ?: '',

                'sms' => env('TWILIO_SMS') ?: '',
            ],
        ],
    ],
];
```

**Comment by hannesvdvreken** [comment]
Yo, I need to stop you right there.

One of the most valuable skills as a developer is to debug a problem to
it's core issue.

Right now you are asking me step by step to solve your problem for you,
which is a lazy and slow approach.

The issue is not with this library or there would be hundreds of tickets
with the same issue. The problem is on your end.

If you find the problem and think it comes from documentation issues, I
would welcome your pull requests to fix the documentation.

**Comment by yelnyaface** [comment]
hi, how do I add newline like \r\n into the SMS or whatsapp message? I tried \n, \r\n, <br>, urlencode() and %0a, but none worked
