### ISSUE TITLE
[Proposal] Support multiple outgoing numbers for text or calls

### ISSUE THREAD

**Issue by andyfleming** [aloha/laravel-twilio#17]
It would be nice to support multiple outgoing numbers for text or calls. It might be nice to give them names/aliases as well.

```php
    /*
    |--------------------------------------------------------------------------
    | From Number
    |--------------------------------------------------------------------------
    |
    | The Phone number registered with Twilio that your SMS & Calls will come from
    |
    */

    'from' => [
        'main_line' => '+12223334444',
        'account_notifications' => '+19998887777'
    ]
```

They could then be accessed by their name:

```php
Twilio::message('account_notifications', '+18085551212', 'Pink Elephants and Happy Rainbows');
```

**Comment by andyfleming** [comment]
Yeah, I agree. I think it would be appropriate to follow that pattern as other things in Laravel do.

**Comment by hannesvdvreken** [comment]
Done. Used an [Interface](https://github.com/aloha/laravel-twilio/blob/master/src/TwilioInterface.php) and a [Manager](https://github.com/aloha/laravel-twilio/blob/master/src/Manager.php) to get this functionality.
