### ISSUE TITLE
Class 'Twilio\Twiml' not found

### ISSUE THREAD

**Issue by edwinjerez** [aloha/laravel-twilio#171]
I want to play a recorded file to certain phone number.
Based on the reference [https://github.com/aloha/laravel-twilio](url) I call the function like this.
$twilio->call($phonenumber, function ($message) {
            $message->say('Nice to meet you');
            $message->play('https://api.twilio.com/cowbell.mp3', ['loop' => 5]);
        });

but it says `Class 'Twilio\Twiml' not found`.
Any recommendations?
Thank you.

**Comment by edwinjerez** [comment]
I checked the Twilio.php in aloha/twilio/src.
it uses Twilio\Twiml, but the locations of Twiml is Twilo\TwiML\TwiML.
but since the TwiML is abstract, it still getting errors.

**Comment by nickfls** [comment]
Apparently, this file is removed in version 5.42.0  as a part of [PR 594](https://github.com/twilio/twilio-php/pull/594)

Are there any plans to update the package?

**Comment by hannesvdvreken** [comment]
Backward compatible error by Twilio. We should cap the upper limit of the twilio package version to `<5.42.0` then.

**Comment by nickfls** [comment]
Do you think it is reasonable to expect it to be done some time soon or just cap at each individual project level @hannesvdvreken ?

**Comment by rayventerprise** [comment]
@hannesvdvreken Okay, are you going to actually do that? If not, this issue should still stay open.

**Comment by kishoresai438** [comment]
Hi Team, does anyone find the solution for this. Suddenly My app verification Call feature is broken.  Previously it was working. I tried to change the name space as per update one. But in  Twilio library , they changed that function to Abstract.

**Comment by zotopteam** [comment]
Someone has solved the problem？ How can I solve it? Who can give me an answe？

**Comment by zotopteam** [comment]
Interim solution：Downgrading twilio/sdk (5.42.2 => 5.41.0)
