### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by shahvirag** [aloha/laravel-twilio#178]
Is there any plan to support laravel 8?
If any can you provide any estimated date, so would be helpful to plan update.
Thank you.

**Comment by hannesvdvreken** [comment]
Feel free to send a PR. Or support via [github sponsoring](https://github.com/sponsors/hannesvdvreken)

**Comment by shahvirag** [comment]
Pull Request #179

**Comment by hannesvdvreken** [comment]
Can you test with `composer require aloha/twilio:"5.0.0-RC3"` and report if it's working fine?

**Comment by shahvirag** [comment]
Sure thing.. will do it tomorrow.
