### ISSUE TITLE
[Proposal] Use new app/config/services.php for Twilio credentials

### ISSUE THREAD

**Issue by andyfleming** [aloha/laravel-twilio#18]
It would be worth considering putting the twilio credentials into the `services.php` file and accessing them from there (since that appears to be the new standard).

```
'twilio' => array(
    'sid' => 'your-twilio-sid',
    'token' => 'your-twilio-token',
),
```

This wouldn't mean that we should completely delete the config in this package though. It may still be important for things like the outgoing phone number, etc. See related issue #17.

**Comment by Quagh** [comment]
This would probably also solve dependency injection?

```php
public function __construct(Twilio $twilio)
    {
        $this->twilio = $twilio;
    }
```

results in

    Unresolvable dependency resolving [Parameter #0 [ <required> $config ]] in class Aloha\\Twilio\\Twilio

**Comment by hannesvdvreken** [comment]
@Quagh The Twilio class is not registered as an alias to 'twilio'. You can do so by adding to some service provider:

```php
$this->app->alias('twilio', 'Aloha\Twilio\Twilio');
```
or in PHP 5.5
```php
$this->app->alias('twilio', Twilio::class);
```

**Comment by hannesvdvreken** [comment]
The next release (current dev-master) will have a new `Aloha\Twilio\TwilioInterface`.

And the config loading in the service provider is changed to use `services.twilio`, which should be formatted like this:

```php
return [
    'twilio' => [
        'default' => 'twilio',
        'connections' => [
            'from' => '',
            'sid' => '',
            'token' => '',
            'ssl_verify' => true,
        ]
    ],
];
```

**Comment by Quagh** [comment]
Awesome :) Looking forward to a stable release.

Funny running into you here by the way. It seems you're managing/contributing to nearly __all__ Laravel packages on GitHub ;p

**Comment by hannesvdvreken** [comment]
Nah :-) only the packages I actually use (for work).
I try to spend some of my spare time on improving the tools I use so my actual work becomes easier.

**Comment by ziming** [comment]
I'm quite confused what does the following commented line mean?

```
return [
    ...
    'twilio' => [
        'default' => 'twilio', // what does default mean? it is already named twilio earlier
        'connections' => [
            'twilio' => [ // why 'twilio again, is it supposed to be renamed to something else?
                'from' => '',
                'sid' => '',
                'token' => '',
                'ssl_verify' => true,
            ],
            'signup' => [
                'from' => '',
                'sid' => '',
                'token' => '',
                'ssl_verify' => true,
            ],
        ],
    ],
];
```

Thank you. Hope for a more detailed explanation of the config settings.

**Comment by aloha** [comment]
// what does default mean? it is already named twilio earlier
Under connections you may have several connection defined.  Setting a default will allow you to use that connection by simply using Twilio::message().

// why 'twilio again, is it supposed to be renamed to something else?
You can rename this to whatever you would like.  But if this doesn't match your default value you will need to always use Twilio::connection('foobar')->message() instead of simply Twilio::message().

**Comment by hannesvdvreken** [comment]
Going to close this.

L4 installs will use `app/config/packages/aloha/twilio/config.php` and
L5 installs will use `config/twilio.php`.
