### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by jibinprabha** [aloha/laravel-twilio#183]
tried to install the package on laravel 7. I am getting this error on final stage.
![image](https://user-images.githubusercontent.com/30919464/99511623-835eab80-29ae-11eb-866e-a9493c287999.png)

**Comment by mocheaz** [comment]
@jibinprabha What was your solution for this?

**Comment by AllCdnBoy** [comment]
Yea, this has become a problem for me too.  I don't think this was resolved, just ignored.

**Comment by AllCdnBoy** [comment]
for me, I had to remove config caching.
