### ISSUE TITLE
Laravel statusCallback not working

### ISSUE THREAD

**Issue by Narendra93** [aloha/laravel-twilio#187]
I have create in laravel phone call in website.Phone call is working fine but callback status not working if user reject or completed call.

My code is.
```
public function phoneCall(Request $request) {
                $call = $this->client->account->calls->create(
                    $phone_number, // Destination phone number
                    $this->from, // Valid Twilio phone number
                    array(
                        "statusCallback" => url("leads/phone-call-events"),
                        "statusCallbackMethod"=>"POST",
                        "record" => True,
                        "url" => "http://demo.twilio.com/docs/voice.xml")
                );
             }   
    public function statusCallbackMethod(Request $request) {
        dd($request);
    }
                ```
Please can you help me for how can i get any status of calling completed or rejected.

**Comment by hannesvdvreken** [comment]
It depends. Is this local? Use ngrok to make your local setup accesible by twilio. Twilio also has tools to debug status callback requests in their dashboard.

Actually this is an issue you should seek help with in the twilio/sdk repository. So closing this one here.

**Comment by Narendra93** [comment]
@hannesvdvreken 
I am getting this error.TwiML response body too large. So what was the solution of this too large response body.

**Comment by hannesvdvreken** [comment]
@Narendra93 learn to find it out yourself. don't expect other people to do your job.
