### ISSUE TITLE
Make receive phone calls from browser

### ISSUE THREAD

**Issue by DeveloperOlivier** [aloha/laravel-twilio#194]
Hi, very handy libraray!

But can this help to make/receive phone calls and have a conversion from the browser from my laravel application ?

Thanks!

**Comment by hannesvdvreken** [comment]
> But can this help to make/receive phone calls and have a conversion from the browser from my laravel application ?

yes.

See twilio documentation.
https://www.twilio.com/docs/voice/tutorials/how-to-respond-to-incoming-phone-calls-php

**Comment by jsmb768ypl** [comment]
> > But can this help to make/receive phone calls and have a conversion from the browser from my laravel application ?
> 
> yes.
> 
> See twilio documentation. https://www.twilio.com/docs/voice/tutorials/how-to-respond-to-incoming-phone-calls-php

Hi sorry to bother you on a closed comment, I see your response but it seems that is only for text based call and answer, is it possible to make browser based calls? so if you click a button it will call a number associated with the button and initiate the call in the browser? 

This is the guide they give but if your package does it already would save tons of time
https://www.twilio.com/docs/voice/tutorials/browser-calls-php-laravel
