### ISSUE TITLE
API Key and Secret support instead of auth token

### ISSUE THREAD

**Issue by agilling521** [aloha/laravel-twilio#197]
The library does not seem to support the new twilio standard of using API keys instead of the root auth tokens.

see URL for twilio documentation. --> https://docs.sendgrid.com/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys

In the perfect world an applet would auto rotate the twilio API key monthly.

**Comment by hannesvdvreken** [comment]
You're confusing Twilio with Sendgrid, I believe.

**Comment by agilling521** [comment]
I am not confused.  :)   
We have 43 master accounts and half a million numbers in twilio.  One of our dev teams decided to use this library. During audit discovered they were using the root auth token.  Our standards for the twilio API is to require the use of API keys instead of the root auth tokens.     Twilio and send grid both support using API keys and it is the preferred method. of login.

https://swimburger.net/blog/dotnet/better-authentication-with-twilio-api-keys

**Comment by bretto36** [comment]
curl -X POST "https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json" \
--data-urlencode "From=+15557122661" \
--data-urlencode "Body=Hi there" \
--data-urlencode "To=+15558675310" \
-u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN

You can now use API Keys as well as Auth Tokens, but you specify the ACCOUNT SID in the url and the API Key credentials in the Authorization header. 

The base twilio package uses 

`public function __construct(string $username = null, string $password = null, string $accountSid = null)`

So you can pass a different account SID with the api credentials

**Comment by bretto36** [comment]
For anyone else who needs this before it's added to the package. I simply created a new class that added it in

<?php

namespace App\Service;

use Twilio\Exceptions\ConfigurationException;
use Twilio\Rest\Client;

class Twilio extends \Aloha\Twilio\Twilio
{
    /**
     * @var string
     */
    protected $accountSid;

    public function __construct(string $accountSid, string $sid, string $token, string $from, bool $sslVerify = true)
    {
        $this->accountSid = $accountSid;

        parent::__construct($sid, $token, $from, $sslVerify);
    }

    /**
     * @return Client
     * @throws ConfigurationException
     *
     */
    public function getTwilio(): Client
    {
        if ($this->twilio) {
            return $this->twilio;
        }

        return $this->twilio = new Client($this->sid, $this->token, $this->accountSid);
    }
}
