### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by hostianer** [aloha/laravel-twilio#22]
Does your package supports Laravel 5 in the future ?
Or do you have a fast fix to install it with L5 ?

**Comment by olsgreen** [comment]
@aloha I hope you don't mind but for those interested, I've put a Laravel 5 version up @ https://github.com/olsgreen/laravel5-twilio. 

At the moment it's more or less a direct drop-in upgrade, with the exception that config is now stored within config/services.php [issue #18]. It also includes my pull request which adds the ability to disable API SSL certificate validation which fixes problems on some OS X installs.

I've kept it in the same namespace for the second, as I don't know whether an L5 version is coming from @aloha, this will make a tiny bit it easier to switch back if needed.

**Comment by hannesvdvreken** [comment]
@olsgreen It's better to make a PR than to clone. Laravel 5 is not out yet, so there are no finalized details on BC breaking changes. 

Once a release is tagged, it will be worth merging in a PR, or to create a new PR.

Until then it is better to make a PR or to write your own service provider that wires this into your application.

**Comment by olsgreen** [comment]
@hannesvdvreken Laravel 5 is feature complete as Taylor confirmed a week or so ago, it's just pending documentation, so no worries of breaking changes. Many Laravel packages are now using L5 as the release version and referencing older versions for L4.

I'm fully aware of the 'best' practices when contributing to repositories, my last pull request has been ignored for months. I ended up making the fixes to get it working and thought I would share my work. I think @aloha is adding me as a contributor so I get the small changes updated and a release that works with L5.

**Comment by hannesvdvreken** [comment]
Alright cool. Thanks for showing how you'd fix it.

Few things to mention: Taylor said he wanted to tag a beta-release last
week. He hasn't done so, yet. Thus it's not final. If he said something
different, please point me to the place where he did so.

**Comment by olsgreen** [comment]
@hannesvdvreken From 5:00 onwards of this video the question of L5 release date comes up. He says that there are 'a few little things' such as a few pull requests to deal with but mainly documentation and that people should 'start hacking around with it' and also that people can 'start basing new projects' on it. In my opinion I'll take this as a green light to start using L5, granted it's not officially tagged, but I'll take his words as meaning there will be no breakages.

**Comment by hannesvdvreken** [comment]
The Laravel podcast you mean? (There's no link in my email notification)
I've listened to that…

**Comment by olsgreen** [comment]
Noop, a different QA session with the DFW meet up. Sorry, I forgot the link and then added it, guessing you didn't get the update. Link below:

https://www.youtube.com/watch?feature=player_embedded&v=XrBoZE_jnSo#t=301

**Comment by hannesvdvreken** [comment]
@olsgreen Possibly this is now working on Laravel 5. I'd like to invite you and test it out. Use a fresh L5 installation and install this with `composer require aloha/twilio:dev-master`. The configuration changed a little but the rest should be pretty backwards compatible.

**Comment by hannesvdvreken** [comment]
I tested it. It works as expected.

**Comment by Kussie** [comment]
Not quite working for me.

Changed the package to use dev-master in my composer file.  Did a composer update and the process dies with the following error:
exception 'ErrorException' with message 'Argument 2 passed to Aloha\Twilio\Manager::__construct() must be of the type array, null given, called in /home/vagrant/wallaby/vendor/aloha/twilio/src/Aloha/Twilio/TwilioServiceProvider.php on line 25 and defined' in /home/vagrant/wallaby/vendor/aloha/twilio/src/Aloha/Twilio/Manager.php:24

**Comment by hannesvdvreken** [comment]
Well, have you tried updating the configuration? We changed the format of the configuration so it keeps working in Laravel 5. Basically the configuration moved to `app/config/services.php` and should have this format: https://github.com/aloha/laravel4-twilio/blob/master/src/config/services.php.

**Comment by Kussie** [comment]
@hannesvdvreken 
Yep added the twilio block to my services.php file and still receiving the same error

**Comment by hannesvdvreken** [comment]
Alright, let me look into this later. If you found the answer in the mean time, feel free to post it here.

**Comment by Kussie** [comment]
@hannesvdvreken 
I found the issue and it was my own complete stupid fault.  Since i am still in the process of doing a test migration to Laravel 5 i had forgotten i had copied services.php to my environment.  Adding it to my environment configs solved that issue.

However i am now experiencing a strange L5 related issue in general, regarding environment settings and it grabbing the wrong values.  It's not isolated to this package though and seems to be related to L5.  Time to create a PHPUnit test and submit over to Taylor.  

Damn silly simple mistakes >.>

**Comment by hannesvdvreken** [comment]
Great to hear you have found the issue. And thanks for trying this unreleased version! If you have any feedback, feel free to post it!

**Comment by Kussie** [comment]
So far so good!  Just need to figure out this environment issue i'm experience with L5 and i'll be give it some proper testing :)

**Comment by andrewcaulfield** [comment]
Hi guys,

I'm having an issue with a recently updated version of Laravel 5. This was all working fine last week but now I'm getting an error in AliasLoader.php

Class 'Aloha\Twilio\Facades\Twilio' not found.

It looks like the folder structure of Aloha may have changed in the vendor folder.

**Comment by hannesvdvreken** [comment]
Again: it is not advised to install this using dev-master. To answer your
question: some classes have been moved around. Change the name of the
facade class in config/app.php to 'Aloha\Twilio\Support\Laravel\Facade'.


Met vriendelijke groeten,
Hannes Van De Vreken
+32472730233

**Comment by andrewcaulfield** [comment]
This is still causing issues.

I think it should be specified in the ReadMe which version of the package we should be pulling in as 'composer require aloha/twilio' pulls in 'dev-master'.

**Comment by aloha** [comment]
@andrewcaulfield when you use composer require it doesn't ask you for a version? It should prompt you like this:  "Please provide a version constraint for the aloha/twilio requirement:"

**Comment by andrewcaulfield** [comment]
@aloha 

![screen shot 2015-03-03 at 12 52 54](https://cloud.githubusercontent.com/assets/3205699/6455123/44f3088c-c1a4-11e4-9432-0852f9e5b57f.png)

**Comment by aloha** [comment]
Can you drop that into a separate issue along with all the details?  Composer version, composer file if you have one in that folder etc.  I've tried to reproduce several ways but without luck.  I was thinking you were  using a different min stability but mine still asks for a version.

**Comment by andrewcaulfield** [comment]
All good. Someone had updated our composer.json to include "minimum stability: dev".

All good.

**Comment by dylanglockler** [comment]
Trying to get this working on a development project - installed through composer but getting
ErrorException in AliasLoader.php line 63:
Class 'Aloha\Twilio\Facades' not found

When I try to send a text.

**Comment by hostianer** [comment]
Did you set the correct namespace ?
Maybe php artisan dump-autoload can also help.

**Comment by dylanglockler** [comment]
dump-autoload resulted in the following:
[ErrorException]                                                                                                                      
  Argument 2 passed to Aloha\Twilio\Manager::__construct() must be of the type array, null given, called in /Users/dylanglockler/Sites  
  /laravel-lovelaundry-5/vendor/aloha/twilio/src/Support/Laravel/ServiceProvider.php on line 26 and defined

**Comment by hostianer** [comment]
By the way: The package currently does not support L5 if you install it ?

**Comment by dylanglockler** [comment]
I thought it supported L5 because of the 'Laravel 4 & 5 Twillio API Integration' at the top of the repository. Doesn't appear to be there yet.

**Comment by SilverPaladin** [comment]
This doesn't install to Laravel 5 it seems. 
```
composer require aloha/twilio 1.0.2 
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aloha/twilio 1.0.2 -> satisfiable by aloha/twilio[1.0.2].
    - Conclusion: remove laravel/framework v5.0.14
    - aloha/twilio 1.0.2 requires illuminate/support 4.* -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
```

**Comment by jv2222** [comment]
I am having the same issue as @SilverPaladin ...

Problem 1
    - Installation request for aloha/twilio 1.0.2 -> satisfiable by aloha/twilio[1.0.2].
    - Conclusion: remove laravel/framework v5.0.14
    - aloha/twilio 1.0.2 requires illuminate/support 4.* -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10,  etc.
    - Installation failed, reverting ./composer.json to its original content.

**Comment by wkolcz** [comment]
I am attempting to use this with L4.2. I loaded the 1.* version into the project along with the twilio\sdk for it. All seems to go well with the composer update but when I publish the config I get 'Aloha\\Twilio\\Support\\Laravel\\ServiceProvider' not found". What do people with L4 do to get it to work?

**Comment by hannesvdvreken** [comment]
In the 1.* version one should use the `Aloha\Twilio\TwilioServiceProvider`.

**Comment by wkolcz** [comment]
Thanks! That seemed to work!

**Comment by wkolcz** [comment]
Sorry to bug you one more time, but what is the L4 Facade? Its not Class Aloha\Twilio\Support\Laravel\Facade

**Comment by hannesvdvreken** [comment]
@wkolcz `Aloha\Twilio\Facades\Twilio`. You can watch the source in https://github.com/aloha/laravel-twilio/tree/1.0.2/src/Aloha/Twilio or in your project's vendor folder.

**Comment by wkolcz** [comment]
I realized that right after I asked for it where to look for it. Thank you again for the help and awesome package.

**Comment by wkolcz** [comment]
Ok, I lied. One more question. When trying to do an automated phone call that you build on the fly with the say methosd, I tried this but got an error. How do set it up in L4 with the Twillo::call?

 

Wally Kolcz

Senior Application Developer

PetPal Manager

586.804.7135

 <mailto:wkolcz@petpalmanager.com> wkolcz@petpalmanager.com

 <http://www.facebook.com/petpalmanager> Friend us on Facebook

**Comment by hannesvdvreken** [comment]
@wkolcz please read the readme file of 1.0.2: https://github.com/aloha/laravel-twilio/blob/1.0.2/README.md.

**Comment by abhijeet9920** [comment]
Hi, I'm using your service with Laravel 5.1.45. Is there any method for adding new verified id?? I'm not able to send message for non-verified caller ids, as it suggests either upgrade your twilio number or verify your number first [here](https://www.twilio.com/console/phone-numbers/verified). So I should verify number first using this [API](https://www.twilio.com/docs/api/rest/outgoing-caller-ids) for adding/posting new verified number but available in twilio/sdk package. Please help me to sort out this problem. Thank you.

**Comment by hannesvdvreken** [comment]
Looks like a question for Twilio support! :-)
