### ISSUE TITLE
Error with laravel 4!! please help

### ISSUE THREAD

**Issue by broy5209** [aloha/laravel-twilio#44]
Services_Twilio_RestException
The requested resource /2010-04-01/Accounts/SMS/Messages.json was not found

**Comment by hannesvdvreken** [comment]
Can you write down some more information? Eg which specific laravel version (`php artisan version`), which version of aloha/twilio, example code to reproduce this. Thanks!

**Comment by cuzifelt1ikeit** [comment]
I'm having the same issue. Laravel framework version 4.2.16. I'm not sure how to find the version of aloha/twilio, but I just added it to my composer file yesterday. I am trying to send a test text in the route file. The code I am using to send the text is: Twilio::message('+1XXXXXXXXXX', 'Test text');

**Comment by cuzifelt1ikeit** [comment]
I actually found out what was going on, for some reason it isn't taking the variables that I set in the services file. Any idea why it isnt?

**Comment by hannesvdvreken** [comment]
Question: are you using a tagged version or dev-master?

**Comment by cuzifelt1ikeit** [comment]
This is what is in my composer file: "aloha/twilio": "~1.0". I'm not sure if that answers the question or not though.

**Comment by aloha** [comment]
I just pulled down 4.2.16 and using "aloha/twilio": "~1.0" and I get a text via Twilio just fine.  Make sure you aren't using the new config layout and are using the 1.0 (4.2 compatible) version.

```php<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | SID
    |--------------------------------------------------------------------------
    |
    | Your Twilio Account SID #
    |
    */

    'sid' => '',

    /*
    |--------------------------------------------------------------------------
    | Access Token
    |--------------------------------------------------------------------------
    |
    | Access token that can be found in your Twilio dashboard
    |
    */

    'token' => '',

    /*
    |--------------------------------------------------------------------------
    | From Number
    |--------------------------------------------------------------------------
    |
    | The Phone number registered with Twilio that your SMS & Calls will come from
    |
    */

    'from' => ''

);

**Comment by cuzifelt1ikeit** [comment]
It works if I enter in the information in the config file supplied by your package, but not when I leave that one empty and use the exact same file in the config folder with the other config files for the app. Is there something I am missing to get it to work that way?

**Comment by hannesvdvreken** [comment]
@cuzifelt1ikeit Use the `php artisan config:publish aloha/twilio` command and modify the generated config file.

**Comment by Sotiris-k** [comment]
@hannesvdvreken this is valuable information. I also couldn't get it work with services.php but with the generated config file it worked. Also to add for those who don't know, the generated file by default is in app/config/packages/aloha/twilio/

Can you change the README with it?

**Comment by hannesvdvreken** [comment]
I will put some more work into it on friday afternoon to make it work with
L5 and L4 without issues, and tag a 2.0.0 release.


Met vriendelijke groeten,
Hannes Van De Vreken
+32472730233

**Comment by Sotiris-k** [comment]
Great news! Thank you! ;)

--

*Web Developer/DesignerSotiris Katsaniotis*

*E: sotiris.katsaniotis@gmail.com <sotiris.katsaniotis@gmail.com>W:
Blizzard.gr <http://bit.ly/18JMjXd>*
*Follow me on: Facebook <http://on.fb.me/1aV1a7a> | Twitter
<http://bit.ly/17Y5wcD> | Google+ <http://bit.ly/157vEPK>*

On 26 February 2015 at 12:58, Hannes Van De Vreken <notifications@github.com
> wrote:

> I will put some more work into it on friday afternoon to make it work with
> L5 and L4 without issues, and tag a 2.0.0 release.
>
>
> Met vriendelijke groeten,
> Hannes Van De Vreken
> +32472730233
>
>
> On Thu, Feb 26, 2015 at 11:53 AM, Sotiris Katsaniotis <

**Comment by andrewcaulfield** [comment]
:+1:

**Comment by CodyPChristian** [comment]
Thanks cause on 4.2 this occurs:

php artisan config:publish aloha/twilio
{"error":{"type":"ErrorException","message":"Argument 2 passed to Aloha\\Twilio\\Manager::__construct() must be of the type array, null given, called in \/vendor\/aloha\/twilio\/src\/Support\/Laravel\/ServiceProvider.php on line 26 and defined","file":"\/vendor\/aloha\/twilio\/src\/Manager.php","line":24}}%

**Comment by hannesvdvreken** [comment]
Check your config.

**Comment by CodyPChristian** [comment]
I did and on L4.2 it was not working. I'm using "aloha/twilio": "~1.0" as the current release doesn't work at all with 4.2. It acts like it sends a message but it does not and does not log any errors. Lastly the error above only occurs via Artisan, if I fire off a SMS via application it works just fine.

**Comment by hannesvdvreken** [comment]
Sorry, there is no `Aloha\Twilio\Manager` in ~1.0 releases. Check the source: https://github.com/aloha/laravel4-twilio/tree/1.0.2

**Comment by CodyPChristian** [comment]
My location is here for config btw: config/packages/aloha/twilio/twilio.php.

What needs to be changed in 1.0 for Aloha\Twilio\Manager?

Thanks

**Comment by CodyPChristian** [comment]
@hannesvdvreken  Any updates?

**Comment by hannesvdvreken** [comment]
I'm busy, sorry.

**Comment by hannesvdvreken** [comment]
Found some time. Have a look at master branch and open PRs. Will publish v2 soon.
