### ISSUE TITLE
composer require aloha/twilio fails with a laravel 5 tree

### ISSUE THREAD

**Issue by Neo-Desktop** [aloha/laravel-twilio#58]
Using version ~1.0 for aloha/twilio
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aloha/twilio 1.0.1 requires twilio/sdk dev-master -> no matching package found.
    - Installation request for aloha/twilio ~1.0 -> satisfiable by aloha/twilio[1.0.1, 1.0.2].
    - Conclusion: remove laravel/framework v5.0.15
    - aloha/twilio 1.0.2 requires illuminate/support 4.* -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.1.0|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.1|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.10|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.11|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.12|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.13|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.14|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.15|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.16|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.17|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.18|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.19|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.2|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.20|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.21|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.22|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.23|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.24|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.25|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.26|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.27|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.28|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.29|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.3|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.30|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.4|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.5|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.6|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.7|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.8|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.1.9|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.1|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.10|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.2|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.3|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.4|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.5|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.6|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.7|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.8|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.0.9|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.15
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.15
    - Installation request for laravel/framework == 5.0.15.0 -> satisfiable by laravel/framework[v5.0.15].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by hannesvdvreken** [comment]
Please read closed issues. Version 1.0.2 is not installable together with Laravel 5.*, version 2.0 will, but is not released yet.

**Comment by Neo-Desktop** [comment]
Could you update your readme then? This is entirely confusing if I can't use it with Laravel 5 http://i.imgur.com/QRdbYLl.png

**Comment by hannesvdvreken** [comment]
The documentation on 1.x releases can be found on the [1.x branch](https://github.com/aloha/laravel-twilio/tree/1.x). Laravel 5 support is not released yet.

**Comment by mrnull** [comment]
Why does you writing "To wire this up in your Laravel project, wether it's built in Laravel 4 or 5" if it is does not working?

**Comment by hannesvdvreken** [comment]
Laravel 5 support starts from the 2.0.0 release, you can test the RC by installing 2.0.0-RC1.

**Comment by mrnull** [comment]
How may I install it? Composer does not found this package.

**Comment by hannesvdvreken** [comment]
Composer did not found this package or composer did not found this version? In order to install the RC version you'll need to lower your minimum-stability to RC or lower.
