### ISSUE TITLE
Error in Readme

### ISSUE THREAD

**Issue by tszaniszlo** [aloha/laravel-twilio#59]
Hi,

In the readme there is a mistake:

Instead of:
'Aloha\Twilio\Support\Laravel\ServiceProvider'
You should use

'Aloha\Twilio\TwilioServiceProvider'

Regards,
Tamás

**Comment by hannesvdvreken** [comment]
If you're using the 1.0.2 release you should look at the 1.x branch for documentation.

https://github.com/aloha/laravel-twilio/tree/1.x
