### ISSUE TITLE
Documentation Incorrect - Causes class load issue in Laravel 4

### ISSUE THREAD

**Issue by niclowe** [aloha/laravel-twilio#61]
Hi

Your service provider documentation is incorrect for laravel 4

Here: https://github.com/aloha/laravel-twilio#laravel-integration

This line

'Aloha\Twilio\Support\Laravel\ServiceProvider',

should be

'Aloha\Twilio\TwilioServiceProvider', 

as otherwise you get a class loading issue.

**Comment by hannesvdvreken** [comment]
Check other issues: #60. You are probably using the 1.0.2 release, so check the readme in the 1.x branch.

**Comment by niclowe** [comment]
yes, the correct path is in THAT file, but NOT in the file that is at the front of your github page.
If you fix this, you'll save people like me hours....

**Comment by aloha** [comment]
@niclowe Expect an update to the README with instructions for 4.X and 5.X respectively soon.  Sorry you had the trouble.

**Comment by InfiniteDevelopment** [comment]
Still not updated. I just installed from composer and this was still an issue for me. I think you need to change it in the docs.

**Comment by hannesvdvreken** [comment]
@InfiniteDevelopment what version do you have installed?

1.0.*? check documentation on [1.x branch](https://github.com/aloha/laravel-twilio/tree/1.x) (no support for Laravel 5)
2.0.0-RCX? Use serviceprovider class `Aloha\Twilio\Support\Laravel\ServiceProvider`.

**Comment by InfiniteDevelopment** [comment]
Aloha\Twilio\Support\Laravel\ServiceProvider doesn't work with "aloha/twilio": "~1.0" which is what composer installed for me. I am also getting Illegal string offset 'sid' for a call. Not sure whats happening.

**Comment by hannesvdvreken** [comment]
You installed `1.0.2` probably because your composer.json says `"aloha/twilio": "~1.0"` (see which versions that means [here](http://semver.mwl.be/#?package=aloha%2Ftwilio&version=~1.0)).

As before mentioned: the 1.0.x version's documentation can be consulted [here](https://github.com/aloha/laravel-twilio/tree/1.x). It says to use the `Aloha\Twilio\TwilioServiceProvider` class.
