### ISSUE TITLE
Could not load package aloha/twilio in http://packagist.org

### ISSUE THREAD

**Issue by srirussel** [aloha/laravel-twilio#63]
The error occurs when I do composer update

Error messages:

1.  [RuntimeException]                                                           
  Could not load package aloha/twilio in http://packagist.org: [UnexpectedVal  
  ueException] Could not parse version constraint : Invalid version string ""

2.[UnexpectedValueException]                                      
  Could not parse version constraint : Invalid version string ""

**Comment by hannesvdvreken** [comment]
What does your require block of your composer.json say? Ideally install "~1" or "~2" with minimum-stability RC or lower to install `2.0.0-RC1`

**Comment by srirussel** [comment]
~1.0

**Comment by srirussel** [comment]
minimum-stability:dev

**Comment by hannesvdvreken** [comment]
These are the versions you will install: http://semver.mwl.be/#?package=aloha%2Ftwilio&version=~1.0&minimum-stability=dev

With a `composer update ` you will try to install the latest commit on the `1.x` branch.

**Comment by srirussel** [comment]
how will I update the other vendor file that I am using if because of this issue composer update is like being blocked

**Comment by hannesvdvreken** [comment]
The latest commit on the 1.x branch is essentially the 1.0.2 release. I suspect your version constraint error is coming from a different package with an invalid composer.json file. You can loop all your dependencies and their sub dependencies to find out.

**Comment by srirussel** [comment]
even if I run this

composer require aloha/twilio:"~1.0"

still gives an error

**Comment by hannesvdvreken** [comment]
Sorry, can't help you: I executed this succesfully

```
vagrant@homestead:/vagrant/tmp$ echo "{}" > composer.json
vagrant@homestead:/vagrant/tmp$ composer require aloha/twilio
Using version ~1.0 for aloha/twilio
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing twilio/sdk (3.12.8)
    Loading from cache

  - Installing illuminate/support (v4.2.17)
    Downloading: 100%         

  - Installing aloha/twilio (1.0.2)
    Loading from cache

Writing lock file
Generating autoload files
vagrant@homestead:/vagrant/tmp$ echo "{}" > composer.json
vagrant@homestead:/vagrant/tmp$ composer require aloha/twilio:"~1.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
vagrant@homestead:/vagrant/tmp$
```

Then I added `"minimum-stability": "dev"` to my composer.json:

```js
{
    "require": {
        "aloha/twilio": "~1.0"
    },
    "minimum-stability": "dev"
}
```

Then I ran composer update.
```
vagrant@homestead:/vagrant/tmp$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing illuminate/support (v4.2.17)
  - Installing illuminate/support (4.2.x-dev db61f3f)
    Cloning db61f3f6d507ce417ca993e1f93585db7efd8b12

  - Removing aloha/twilio (1.0.2)
  - Installing aloha/twilio (1.x-dev 47e69c0)
    Cloning 47e69c0fba9e2e65edf48c6d4125e544cd0140d7

Writing lock file
Generating autoload files
vagrant@homestead:/vagrant/tmp$
```

**Comment by hannesvdvreken** [comment]
I closed this but feel free to comment if you made some progress or found out something. Use [semver.mwl.be](http://semver.mwl.be) to check version contraints and according installable versions.

**Comment by srirussel** [comment]
I resolve this by using

composer self-update

I see it right here

https://laracasts.com/discuss/channels/general-discussion/anyone-else-getting-an-odd-composer-update-error-today

**Comment by hannesvdvreken** [comment]
Ah yes, the `^` (caret) sign. :+1: I blogged about it last week. blog.madewithlove.be/post/tilde-and-caret-constraints
