### ISSUE TITLE
No AMD Support

### ISSUE THREAD

**Issue by InfiniteDevelopment** [aloha/laravel-twilio#66]
I have dug into your docs and code base and have come to the conclusion that your package doesn't support it. Can you confirm?

**Comment by hannesvdvreken** [comment]
Sorry, what's AMD? The processor thing? If PHP supports it, this package can run on it.

**Comment by InfiniteDevelopment** [comment]
Answering Machine Detection. It's a attribute for the rest call. Where is the rest call happening?

**Comment by hannesvdvreken** [comment]
I'm not 100% familiar with the Twilio SDK, but from what I can read in the Twilio documentation you can add an option to the call method.

```php
$twilio->call($to, $url, ['IfMachine' => 'Hangup']);
$twilio->call($to, $url, ['IfMachine' => 'Continue']);
```
