### ISSUE TITLE
Cannot install through Composer on Laravel 5

### ISSUE THREAD

**Issue by thewinterwind** [aloha/laravel-twilio#68]
Please see screenshot attached. Do I need to seperately require `twilio/sdk dev-master`

I would imagine its already a dependency of this package.

![screen shot 2015-04-19 at 9 41 44 am](https://cloud.githubusercontent.com/assets/2460820/7217803/80fe10e4-e678-11e4-96e9-8663f470bdff.png)

**Comment by elliotlings** [comment]
Version 1 is Laravel 4.
You'll want to use dev-master or 2.0.0-RC2

**Comment by hannesvdvreken** [comment]
What @elliotlings said.

`twilio/sdk` is a dependency of `aloha/twilio` so you don't have to install it yourself.
When you're using Laravel 5, we advise you to install with version constraint `~2.0@RC` of `aloha/twilio`, otherwise you can install any version you like.
