### ISSUE TITLE
Upgrading twilio twilio/sdk to 4.0

### ISSUE THREAD

**Issue by elliotlings** [aloha/laravel-twilio#69]
Do you think we are OK to upgrade to 4.0?
https://github.com/twilio/twilio-php/blob/latest/CHANGES.md

I want to add some functionality for lookups but their library is broken in composer for the lookups class. I'm gonna put a fix in and it'll probably come under the 4.x tag.

**Comment by hannesvdvreken** [comment]
If you managed to fix it and they accepted the PR and tagged a new release, let me know the exact release number.

**Comment by hannesvdvreken** [comment]
Here's the differences between 3.12.0 (current required lowest version) and 4.0.0:

https://github.com/twilio/twilio-php/compare/3.12.0...4.0.0

I'll browse that later when I have time and look for backwards incompatible changes that might affect us. I don't thrust them following semver, so I'll have to manually verify.

If it's ok we'll probably update our version constraint of `twilio/sdk` to `~3.12|~4.0`.

**Comment by Charkhan** [comment]
When do you plan to do this ? I'm using your package and I need extra functionalities (like lookups).

But in version 3.12, lookups doesn't work like said before.
And the latest version has the fix !

Thanks :)

**Comment by hannesvdvreken** [comment]
Fixed since 2.0.0-RC3
