### ISSUE TITLE
Integration with Laravel 5.0 is failing

### ISSUE THREAD

**Issue by pracman** [aloha/laravel-twilio#70]
Was trying to use with Laravel 5.0.  After typing in composer require aloha/twilio  got following error
" Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems."

Any idea what is going wrong?

**Comment by hannesvdvreken** [comment]
Nothing is going wrong. Try using the command `composer require aloha/twilio:"~2.0@RC"`. Please not this is a prerelease.

**Comment by pracman** [comment]
Would you suggest to use it or wait for release?  Thanks

**Comment by hannesvdvreken** [comment]
You can use it on own risk. You can help out by using it and reporting bugs.
