### ISSUE TITLE
Something missing from instructions? Or this package just doesn't work

### ISSUE THREAD

**Issue by kureci** [aloha/laravel-twilio#71]
I follow the instructions, install the package via composer, and then add the service provider in `app.config` and also register the Facade. However, when I try the artisan command `twilio:sms` I get Fatal error saying `class Aloha\Twilio was not found in ..compiled.php`

I do run `composer dump-autoload` after installing the package. That doesn't solve the issue.

Also, you give `Aloha\Twilio\Support\Laravel\ServiceProvider` as the service provider path, but your package folder structure suggests that it should be `Aloha\Twilio\ServiceProvider` instead. same with the Facade. However that doesn't solve the Fatal Error issue either!

So, what am I missing?

**Comment by hannesvdvreken** [comment]
You have a version from the 1.x branch installed. Please use those instructions.
