### ISSUE TITLE
Services_Twilio_RestException in Twilio.php line 303:

### ISSUE THREAD

**Issue by sdeering** [aloha/laravel-twilio#77]
Hi guys, sorry to post this here, but was wondering if there is a reason why I can't use Twilio to send an SMS to my Australian Mobile.

I have:
1. paid account setup
2. twolio number with international support
3. using the L5 package https://github.com/aloha/laravel-twilio

![image](https://cloud.githubusercontent.com/assets/1787454/8448012/0bb98838-2005-11e5-8f36-e1c2b7dc7ad2.png)

I tried this tool by Twilio and it sent to my mobile successfully so doesn't look like a carrier issue.

Any help would be much appreciated.

**Comment by sdeering** [comment]
Ok, I think I solved it. I have 2 Twilio numbers, the 1 which sends the SMS (FROM) needs to be a mobile not a landline number.

**Comment by hannesvdvreken** [comment]
Thanks for sharing! :+1:
