### ISSUE TITLE
Undefined method message()

### ISSUE THREAD

**Issue by isbkch** [aloha/laravel-twilio#81]
Laravel 5.1.7.
I'm getting:

```Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()```

I already use ```Twilio;``` And followed the example to send messages:

```$twilio = new Twilio($sid, $token, $from );
$twilio->message('+15146632603', 'Pink Elephants and Happy Rainbows');```

**Comment by hannesvdvreken** [comment]
@isbkch I'll take a look to see if I can reproduce this. Please let me know if you fixed it on your own.

**Comment by hannesvdvreken** [comment]
Sorry, the facade seems to work. I tried both fully qualified class name, and laravel's facade aliasing. Was the service provider correctly registered? Use this service provider to be sure: `Aloha\Twilio\Support\Laravel\ServiceProvider`.

**Comment by DhanapalMadheswaran** [comment]
Call to undefined method Aloha\Twilio\Support\Laravel\Facade::message()

**Comment by rashigoyal03** [comment]
Any update on this?

**Comment by hannesvdvreken** [comment]
@rashigoyal03 can you double check the version of this package you have installed, and if you setup namespacing correctly and have the service provider registered?

cheers.

**Comment by joshblevins85** [comment]
Any update on this?
Same error here
