### ISSUE TITLE
This package doesn't work on laravel 5.1

### ISSUE THREAD

**Issue by Al3xR0** [aloha/laravel-twilio#82]
- aloha/twilio 1.0.1 requires twilio/sdk dev-master -> no matching package found.
- Installation request for aloha/twilio ^1.0 -> satisfiable by aloha/twilio[1.0.1, 1.0.2].
- Conclusion: remove laravel/framework v5.1.8
- Conclusion: don't install laravel/framework v5.1.8
- aloha/twilio 1.0.2 requires illuminate/support 4.* -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16,
 v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.
2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by hannesvdvreken** [comment]
I suggest installing 2.0.0-RC5.

**Comment by Al3xR0** [comment]
Thanks it works. Is this version under development?

**Comment by hannesvdvreken** [comment]
Yes, it's a Release Candidate, probably going to tag it as stable 2.0.0 tomorrow. If you have a play with it and have some comments, please shoot them in the gitter.im chat.
