### ISSUE TITLE
SSL operation failed

### ISSUE THREAD

**Issue by lmatab** [aloha/laravel-twilio#84]
Hello,

I am working with Laravel  5.0

I did  follow  all the steps to use your twilio package but I get this a  screen with:

file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Any Ideas  how to solve it?

**Comment by lmatab** [comment]
I just  solved.

If you are  having this  problem  just  run this  commands:

apt-get update
apt-get install php5-curl

This will update your  libcurl as shown in this  link:

http://twilio-php.readthedocs.org/en/latest/faq.html

Thanks a lot  for this  great  package.

**Comment by hannesvdvreken** [comment]
You're welcome.
