### ISSUE TITLE
laravel crashes when producing twilio errors

### ISSUE THREAD

**Issue by jerik** [aloha/laravel-twilio#85]
Hi, 

I want to use your twilio library. I installed and configured (my) Test SID and Token like in the readme.md described. When I am sending a valid sms, everything works like expected. But when I try to develop the errorhandling based on the [test-credentials](https://www.twilio.com/docs/api/rest/test-credentials) it crashes. I try to catch the `Services_Twilio_RestException`, but the catch is never reached... 

Heres the code: 

    use Illuminate\Database\Eloquent\Model;
    use Aloha\Twilio\TwilioInterface;

    class Activation extends Model {
        protected $fillable = array( 'a', 'b', 'c');
        public static function send() {

            // Testaccount
            $toNumber = '+15005550006'; // valid number; works fine
            $toNumber = '+15005550001'; // @todo will throw an exeption, and breaks the app
            try {
                \Twilio::message( $toNumber, 'Pink Elephants and Happy Rainbows');
            } catch ( Services_Twilio_RestException $e ) {
                elog( 'EACT', $e->getMessage(  ) , __FUNCTION__ );
            }
        }
    }

What I get is the following: 

    Whoops, looks like something went wrong.
    Services_Twilio_RestException in /path/to/my/laravel/vendor/twilio/sdk/Services/Twilio.php line 297 
    Exception_message: The &#039;To&#039; number +15005550001 is not a valid phone number.

I expect this error, but not that the app crashes. Any hint how to handle the error handling for the Services_Twilio_RestException?

**Comment by hannesvdvreken** [comment]
```php
App::error('Services_Twilio_RestException', function ($exception) {
    ...
});
```

Should help. If not: ask for help in the Laravel IRC or slack channel.

**Comment by jerik** [comment]
As I was in a namespace the correct catch statement is: 
    } catch ( \Services_Twilio_RestException $e ) {

now it works
