### ISSUE TITLE
Expose Services_Twilio

### ISSUE THREAD

**Issue by cyberhuman** [aloha/laravel-twilio#86]
Is it possible to make Twilio::getTwilio() public so it is possible to use API calls not yet supported by this package?
Thanks.

**Comment by hannesvdvreken** [comment]
I will in version 2.1.0.

**Comment by hannesvdvreken** [comment]
You will have to

```php
Twillio::defaultConnection()->getTwilio();
Twillio::from('+31123123123')->getTwilio();
```

though. Because the Facade connects to the Manager class, and the `getTwilio` method is a method on the Twilio class.

**Comment by hannesvdvreken** [comment]
Sorry for the inexcusable delay.

Upgrade to version `^1.2` to use this feature.
Both `Twilio::getTwilio()` and `Twilio::from($from)->getTwilio()` are now possible.

**Comment by hannesvdvreken** [comment]
Closing this now.
