### ISSUE TITLE
How to generate Twiml from `Twilio` object?

### ISSUE THREAD

**Issue by reinink** [aloha/laravel-twilio#87]
Prior to 1f709bc819aeaf6d361b9bda60b3ad6ff5349fa3, the `twiml()` method was public, giving a quick way to generate Twiml if you had an instance of your `Twilio` object. However, now that this is private, it appears you need to instantiate separately, which is much less convenient. Is there a particular reason for this change? Is there a recommended way to do this? Thanks!

**Comment by hannesvdvreken** [comment]
You can use:

```php
$twiml = new Services_Twilio_Twiml();
$output = $twiml->__toString();
// or: $output = (string) $twiml;
```

You can also use IoC container to create a new Services_Twilio_Twiml object.

**Comment by hannesvdvreken** [comment]
Whoops wrong button

**Comment by hannesvdvreken** [comment]
The particular reason for this is because it's an implementation detail. What would a null object return? It's a trivial method, so you can do what this method did by yourself.

**Comment by reinink** [comment]
Yeah, that totally makes sense. Thanks Hannes!
