### ISSUE TITLE
Class not found issue in creating a sms

### ISSUE THREAD

**Issue by mpgbis-dinesh** [aloha/laravel-twilio#88]
Hi Aloha,

FatalErrorException in TicketsController.php line 60:
Class 'App\Http\Controllers\Aloha\Twilio\Twilio' not found

Error comes up whenever i start to send a sms to user.

I follow all the steps that have mention in your READ ME but it facing the error kindly assist.

**Comment by hannesvdvreken** [comment]
Morning Dinesh,

I bet that you are using the Facade inside a controller. I think that you must import the class first:

```php
use Aloha\Twilio\Twilio;
```

above your controller class declaration.
