### ISSUE TITLE
Newline not appearing in sent sms

### ISSUE THREAD

**Issue by enisto** [aloha/laravel-twilio#94]
The issue I am facing is that, after reading the documentation of twilio I began using \n in my SMS body, to insert a new line, but on the receiver end, never is the new line appearing.

**Comment by hannesvdvreken** [comment]
Try opening a support ticket with the twilio sdk. Can't really help.

**Comment by enisto** [comment]
I just tried to curl direct toTwilio api and I received a sms with new lines, just for curiosity do the libary escape the special characters somewhere in the code ?

**Comment by enisto** [comment]
I found why this happened, I was using single quoted string instead of dobule quoted string. Thanks!

**Comment by hannesvdvreken** [comment]
Good! Happy holidays
