### ISSUE TITLE
Update documentation to reflect capability

### ISSUE THREAD

**Issue by moh-abk** [aloha/laravel-twilio#95]
Your documentation is not very complete.
You mentioned you can have a default config file but never showed how to use it.
Please update documentation.

I have the below code for sending out text messages and have no way of converting it using your documentation.

    $account_sid = 'xxx'; 
    $auth_token = 'xxx'; 
    $client = new Services_Twilio($account_sid, $auth_token);
    $clientx = new Lookups_Services_Twilio($account_sid, $auth_token);
    $number = $clientx->phone_numbers->get($mobilePhone, array("CountryCode" => "GB"));
    $client = new Services_Twilio($account_sid, $auth_token); 
    $client->account->messages->create(array( 
	'To' => $number->phone_number, 
	'From' => "TWILIO", 
	'Body' => "Ahoy from qwickGrub! Enter $code on the sign up page to verify your account.",   
    ));

I have installed it and have setup my credentials in the config file. I have then inserted `Use Twilio;` in my controller.

I have added the Facade and Alias.

**Comment by hannesvdvreken** [comment]
Have you added the service provider as well?

If the documentation is incorrect, you can create a pull request to improve it. I will gladly accept it.

**Comment by hannesvdvreken** [comment]
Ping?

**Comment by moh-abk** [comment]
Still can't get this to work correctly - `class not found`

**Comment by hannesvdvreken** [comment]
Closing this for now as I believe you're doing something wrong which is more PHP related that with this package.

If you post your question on stackoverflow there will be a much larger group of people reading your question and capable of asking you the right additional question to get to a solution.
