### ISSUE TITLE
[Services_Twilio_RestException] The requested resource /2010-04-01/Accounts//Messages.json was not found

### ISSUE THREAD

**Issue by knightmoverchan** [aloha/laravel-twilio#96]
I am stuck in here, please help.

**Comment by hannesvdvreken** [comment]
Not a :+1: description. I doubt you're going to find much help like that. Sorry.

**Comment by hannesvdvreken** [comment]
Closing this. Don't let this stop you from looking for answers or posting a more descriptive problem. Also if you found an answer to your question, you can still post it here.
