### ISSUE TITLE
Slightly more thorough examples of usage

### ISSUE THREAD

**Issue by danken00** [aloha/laravel-twilio#97]
Hi mate, thanks for your time and effort on this plugin. I have a couple of questions I hope you can help with. In your instructions you mention creating the Twilio object:

    $twilio = new Aloha\Twilio\Twilio($accountId, $token, $fromNumber);

And passing in the `accountId`, `token` and `fromNumber`. You also have a pre-built config file we can use. If we conform to your configuration file layout, then wouldn't it be possible to automatically load the configuration into the Twilio object instead of manually having to pass it in when creating it? This would make creating Twilio objects much cleaner.

The other issue I'm having is that when I try to use the Facade (which doesn't require the account, token or from number, which is attractive), like so:

    Twilio::from('twilio')->message('12345', 'Go go go!');

I get the following error:

     Call to undefined method Aloha\Twilio\Twilio::from()

And when I remove the `use` statement at the top of the page (`use Aloha\Twilio\Twilio;` which I don't think is necessary for facades) I get:

    Class 'App\Models\Twilio' not found

I've added the service provider: `Aloha\Twilio\Support\Laravel\ServiceProvider::class`
And the facade: `'Twilio' => Aloha\Twilio\Support\Laravel\Facade::class`

If you could point me in the right direction I'm happy to update the documentation.

**Comment by hannesvdvreken** [comment]
First:

When you're in the `App\Models\` namespace (or any other namespace), you should add `use Twilio;` or `use Aloha\Twilio\Support\Laravel\Facade as Twilio;`.

```
Call to undefined method Aloha\Twilio\Twilio::from()
```

Definitely something wrong with the imports or facade configuration. Check which version of `aloha/twilio` you have installed and which class name the facade class has.

**Comment by danken00** [comment]
Hey Hannes,

Sorry for wasting your time. Turns out I didn't quite get the grasp of Facades beforehand and something was weird in my setup. Following your instructions got me going perfectly, and it seems the plugin DOES use the config by default, so all good.

I've made a couple of changes to the `readme.md` (to help idiots like me) and created a pull request. Thanks for all your help!

**Comment by hannesvdvreken** [comment]
No problem. Glad to have helped out. Thanks for the pull request.
