### ISSUE TITLE
Create Call Script in App

### ISSUE THREAD

**Issue by alexhackney** [aloha/laravel-twilio#99]
Is it possible to write the entire script in the controller? 

Meaning I want to call someone, say something, then wait for a response and record that to the database.

As far as I can tell I would need to publish the twiml xml file to my public directory and then based on their response place a request back in to my app to confirm the response.

Thanks for the package though really helpful!

**Comment by hannesvdvreken** [comment]
You don't have to.

You can use 
```php
$twilio->call('+18085551212', function ($message) {
    $message->say('Hello');
    $message->play('https://api.twilio.com/cowbell.mp3', ['loop' => 5]);
});
```

Which will use the twiml echo service to make a public twiml page based on the GET input.
https://github.com/aloha/laravel-twilio/blob/master/src/Twilio.php#L91

**Comment by hannesvdvreken** [comment]
The other question: tbh, I don't have any experience with catching the response or anything so you'll have to look in the Twilio SDK documentation
